logging:
  config: classpath:config/log4j-spring.xml

spring:
  profiles:
    active: dev

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.isoftstone.qmp.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  # configLocation: classpath:mybatis/mybatis-config.xml
  # 启用下划线转驼峰
  configuration:
    map-underscore-to-camel-case: true
